// src/lib/components/Status.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { DiscordStatus } from "$lib/types/lanyard";
  import { getLanyardContext } from "$lib/context/lanyard.svelte";

  interface Props {
    children: Snippet;
  }

  let { children }: Props = $props();

  const statusColors: Record<string, string> = {
    online: "bg-green-500",
    idle: "bg-yellow-500",
    dnd: "bg-red-500",
    offline: "bg-gray-500",
  };

  const statusMappings: Record<DiscordStatus, string> = {
    online: "Online",
    idle: "Idle",
    dnd: "Do Not Disturb",
    offline: "Offline",
  };

  const lanyard = getLanyardContext();

  let discordStatus = $derived(lanyard.data.discord_status);
  let color = $derived(statusColors[discordStatus] ?? "bg-gray-500");
  let status = $derived(statusMappings[discordStatus] ?? "Offline");
</script>

<aside class="flex items-center gap-x-2 text-sm font-semibold dark:text-gray-400">
  <span class={`ml-1 h-3 w-3 rounded-full md:ml-0 ${color}`}></span>
  <p>{status}</p>
  &mdash;
  {@render children()}
</aside>

// src/components/Status.tsx
"use client"

import { BsSpotify } from "react-icons/bs"
import { type LanyardData, useLanyard } from "react-use-lanyard"
import type { ReactNode } from "react"

import { DISCORD_USER_ID } from "@/util"
import ExternalLink from "@/components/ExternalLink"

const statusColors = {
  online: "bg-green-500",
  idle: "bg-yellow-500",
  dnd: "bg-red-500",
  offline: "bg-gray-500",
} as const

const statusMappings = {
  online: "Online",
  idle: "Idle",
  dnd: "Do Not Disturb",
  offline: "Offline",
} as const

type SpotifyStatusProps = {
  data: LanyardData["spotify"]
}

function SpotifyStatus({ data }: SpotifyStatusProps) {
  if (!data) return null

  const { artist, song, track_id } = data

  const spotifyUrl = `https://open.spotify.com/track/${track_id}`

  return (
    <>
      <span className="hidden md:inline">&mdash;</span>
      <div className="mb-2 md:mb-0">
        <div className="flex gap-x-2">
          <BsSpotify className="text-green-500" size={20} />
          <ExternalLink href={spotifyUrl} title={`${song} by ${artist}`}>
            {song}
          </ExternalLink>
        </div>
      </div>
    </>
  )
}

type Props = {
  children: ReactNode
  initialData: LanyardData
}

export default function Status({ children, initialData }: Props) {
  const { data } = useLanyard({ userId: DISCORD_USER_ID })

  const { discord_status, spotify } = data?.data ?? initialData

  const color = statusColors[discord_status]

  const status = statusMappings[discord_status]

  return (
    <>
      <div className="flex gap-x-2">
        <div className="flex items-center gap-x-2">
          <span className={`ml-1 h-3 w-3 rounded-full md:ml-0 ${color}`} />
          <p className="text-left">{status}</p>
        </div>
        &mdash;
        {children}
      </div>
      <SpotifyStatus data={spotify} />
    </>
  )
}
